### ISSUE TITLE
jackson-module-paranamer don't include the license file

### ISSUE THREAD

**Issue by puntogil** [FasterXML/jackson-module-paranamer#12]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
All java source files are without license headers. Please, confirm the licensing of code and/or content/s
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
thanks
regards

**Comment by cowtowncoder** [comment]
Added, thank you for pointing this out.
